spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres

camunda.bpm.admin-user:
  id: demo
  password: 1234

server:
  port: 8090


